# Generated by Django 2.0.5 on 2018-06-14 08:21

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(blank=True, default='/static/images/default_pic.jpg', null=True, upload_to=posts.models.upload_location),
        ),
    ]
